# DESCRIPTION OF R SCRIPT
# =============================================================================#
# This script is designed for processing analysis data generated by SeekDeep
# (selectedClustersInfo). It handles both single and multiple file scenarios based
# on the data available for a given study, run, and date. The purpose is to read and
# preprocess the data, ensuring it is ready for downstream analysis. The script
# dynamically adjusts to the number of available data files:
#
# 1. Single File Processing:
#    When only one file matches the specified pattern, the script reads this file,
#    assigns a default source label, and filters out any untranslatable entries.
#
# 2. Multiple Files Processing:
#    If multiple files are present, the script reads each file, merges the data, and
#    applies the same preprocessing steps as in single file processing.
#
# After processing, the script identifies and displays unique genetic markers from
# the data, which assists in understanding the variety of genetic information
# available for further studies.
#
# Dependencies: dplyr, readr, tidyverse
# =============================================================================#



# Construct the full path for file checking
# -----------------------------------------------------------------------------#
full_path <- paste0(PATH_STUDY, PATH_RUN, PATH_ANALYSIS)



# List all files that match the pattern
# -----------------------------------------------------------------------------#
file_list <- list.files(path = full_path, pattern = "^selectedClustersInfo.*\\.gz$", full.names = TRUE)



# Check if multiple files need to be processed or just one
# -----------------------------------------------------------------------------#
if (length(file_list) == 1) {
  # Processing a single file
  raw_selectedClustersInfo <- read_tsv(file_list, col_types = cols(), show_col_types = FALSE) %>%
    mutate_all(as.character) %>%  # Convert all columns to character
    mutate(source = "None") %>%
    filter(! str_detect(h_AATyped, "Untranslatable|\\*") | c(is.na(h_AATyped) & !is.na(h_AATyped)))

} else if (length(file_list) > 1) {
  # Processing multiple files
  raw_selectedClustersInfo <- file_list %>%
    map_dfr(~ read_tsv(.x, col_types = cols(), show_col_types = FALSE) %>%
              mutate_all(as.character)) %>%  # Convert all columns to character
    mutate(source = "None") %>%
    filter(! str_detect(h_AATyped, "Untranslatable|\\*") | c(is.na(h_AATyped) & !is.na(h_AATyped)))
}




# Check what markers are available
# -----------------------------------------------------------------------------#
available_markers <- unique(raw_selectedClustersInfo$p_name)



# remove temporary objects
# -----------------------------------------------------------------------------#
rm(file_list, full_path)



##___print a message in the console ----
# -----------------------------------------------------------------------------#

# Using yellow for the border
cat("\033[1m\033[33m", "\n##############################################################", "\033[0m")

# Using purple (magenta) for the data availability message
cat("\033[1m\033[35m", "\nData from the following targets is available for analysis:", "\033[0m")

# Using green for the available markers
cat("\033[1m\033[32m", "\n", paste(available_markers, collapse = ", "), "\033[0m")

# Yellow for the border again
cat("\033[1m\033[33m", "\n##############################################################\n", "\033[0m")


